## DATABASE ##

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

  application:
    name: testPersonJMeterTask

  datasource:

    url: jdbc:h2:mem:testdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000
  flyway:
    baseline-on-migrate: true
    url: jdbc:h2:mem:testdb
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db.migration
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect